# docker-compose.yml
version: "2.0"

services:
  metadata:
    build: ./
    env_file:
     - ./.env.test
    environment:
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE: dev
      DATABASE_LOGGING: 1
      DATABASE_HOST: maria.host
      DATABASE_DIALECT: mariadb
      SERVER_PORT: 8080
      TMDB_API_KEY: ${TMDB_API_KEY}
    restart: always
    links:
      - maria:maria.host
      - rabbitmq:rabbitmq.host
      - elasticsearch:elasticsearch.host
    depends_on:
      - maria
      - elasticsearch
      - rabbitmq
    volumes:
      - ./:/home/node/server
    ports:
      - 8080:8080
    command: [
      wait-for-it.sh, "maria.host:3306", -t, "120", -s, --,
      wait-for-it.sh, "rabbitmq.host:5672", -t, "120", -sa, "10", -s, --
      node, ./node_modules/.bin/nodemon, run.js, migrate, server
    ]

  maria:
    image: mariadb:10.3
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./data/maria:/var/lib/mysql
    ports:
      - 3306:3306
    
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 3001:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:5.4
    ports: 
      - 9200:9200
    volumes:
      - ./data/es:/usr/share/elasticsearch/data 